//
// Copyright (c) Thomas Nägele and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.
//

/*
 * generated by Xtext 2.12.0
 */
package nl.ru.sws.dsl.lighting.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class BuildingScopeProvider extends AbstractBuildingScopeProvider {

}
